import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {
 Activity, AlertCircle, ArrowLeft, Award, Bell, Cake, CalendarDays, Camera, Check,
 CheckCircle2, ChevronRight, Clock3, CreditCard, Dumbbell, FileText, HeartPulse,
 Home, ListChecks, LogOut, Menu, MessageCircle, MoreVertical, Plus, QrCode, Search,
 Settings, ShieldCheck, Star, Target, TrendingDown, TrendingUp, UserCheck, UserRound,
 Users, UserX, Wallet, X, Zap
} from 'lucide-react';
import './styles.css';

const TIMES=['06:00','07:00','08:00','09:00','10:00','11:00','12:00','13:00','14:00','18:00','19:00','20:00'];
const STORAGE='powerfit-v16-state';
const TEACHERS=[
{id:1,name:'João Martins',active:true,slots:['06:00','07:00','08:00','18:00','19:00']},
{id:2,name:'Ana Costa',active:true,slots:['07:00','08:00','09:00','10:00','18:00']},
{id:3,name:'Lucas Silva',active:true,slots:['06:00','07:00','09:00','10:00','19:00']},
{id:4,name:'Camila Rocha',active:true,slots:['08:00','09:00','10:00','18:00','20:00']},
{id:5,name:'Rafael Lima',active:true,slots:['07:00','09:00','10:00','19:00','20:00']},
{id:6,name:'Júlia Alves',active:false,slots:['18:00','19:00']}
];
const STUDENTS=[
{id:1,name:'Carol Santos',plan:'Plano Mensal',payment:'atrasado',status:'Ativo',birthday:'1990-09-07',due:'10/09/2026',value:149.9,height:1.66,weight:108,goal:65,initialWeight:118,frequency:82,monthlyWorkouts:18,phone:'(21) 99999-9999',email:'carol.santos@email.com'},
{id:2,name:'Juliana Lima',plan:'Wellhub',payment:'pago',status:'Ativo',birthday:'1995-09-12',due:'12/09/2026',value:0,height:1.64,weight:72,goal:68,initialWeight:75,frequency:91,monthlyWorkouts:20},
{id:3,name:'Marcos Silva',plan:'Plano Mensal',payment:'pago',status:'Ativo',birthday:'1988-09-18',due:'15/09/2026',value:149.9,height:1.78,weight:91,goal:84,initialWeight:96,frequency:74,monthlyWorkouts:15},
{id:4,name:'Beatriz Oliveira',plan:'Plano Mensal',payment:'pago',status:'Ativo',birthday:'1997-09-25',due:'25/09/2026',value:149.9,height:1.62,weight:69,goal:63,initialWeight:72,frequency:88,monthlyWorkouts:19},
{id:5,name:'Felipe Souza',plan:'Plano Trimestral',payment:'pago',status:'Ativo',birthday:'1992-10-04',due:'04/10/2026',value:399.9,height:1.8,weight:88,goal:82,initialWeight:92,frequency:69,monthlyWorkouts:13},
{id:6,name:'Ana Souza',plan:'Plano Mensal',payment:'atrasado',status:'Inadimplente',birthday:'1991-09-10',due:'10/09/2026',value:149.9,height:1.67,weight:76,goal:68,initialWeight:79,frequency:53,monthlyWorkouts:9},
{id:7,name:'Paula Mendes',plan:'Plano Mensal',payment:'pago',status:'Ativo',birthday:'1994-09-07',due:'07/09/2026',value:149.9,height:1.7,weight:71,goal:66,initialWeight:74,frequency:96,monthlyWorkouts:22},
{id:8,name:'Renato Gomes',plan:'Plano Mensal',payment:'pago',status:'Ativo',birthday:'1990-09-21',due:'21/09/2026',value:149.9,height:1.74,weight:84,goal:79,initialWeight:87,frequency:61,monthlyWorkouts:12}
];
const BOOKINGS={
'06:00':['Marcos Silva','Juliana Lima','Carol Santos','Felipe Souza','Beatriz Oliveira'],
'07:00':['Carolina Santos','Juliana Lima','Marcos Silva','Beatriz Oliveira','Felipe Souza','Paula Mendes','Renato Gomes'],
'08:00':['Beatriz Oliveira','Felipe Souza','Juliana Lima','Paula Mendes'],
'09:00':['Marcos Silva','Ana Souza','Renato Gomes','Beatriz Oliveira','Juliana Lima','Felipe Souza'],
'10:00':['Beatriz Oliveira','Felipe Souza'], '18:00':['Carol Santos','Ana Souza','Paula Mendes','Renato Gomes'],
'19:00':['Juliana Lima','Marcos Silva','Felipe Souza','Paula Mendes'], '20:00':['Beatriz Oliveira']
};
const HISTORY={
'Carol Santos':{'João Martins':8,'Ana Costa':3,'Camila Rocha':5,'Lucas Silva':1,'Rafael Lima':2},
'Juliana Lima':{'João Martins':2,'Ana Costa':9,'Camila Rocha':6,'Lucas Silva':3,'Rafael Lima':1},
'Marcos Silva':{'João Martins':7,'Ana Costa':2,'Camila Rocha':4,'Lucas Silva':8,'Rafael Lima':2},
'Beatriz Oliveira':{'João Martins':1,'Ana Costa':6,'Camila Rocha':9,'Lucas Silva':3,'Rafael Lima':4},
'Felipe Souza':{'João Martins':4,'Ana Costa':3,'Camila Rocha':2,'Lucas Silva':7,'Rafael Lima':8},
'Ana Souza':{'João Martins':5,'Ana Costa':4,'Camila Rocha':6,'Lucas Silva':2,'Rafael Lima':1},
'Paula Mendes':{'João Martins':10,'Ana Costa':7,'Camila Rocha':3,'Lucas Silva':2,'Rafael Lima':4},
'Renato Gomes':{'João Martins':6,'Ana Costa':2,'Camila Rocha':1,'Lucas Silva':5,'Rafael Lima':3}
};
const ASSESSMENTS=[{id:1,student:'Carol Santos',date:'02/09/2026',professor:'João Martins',weight:108,waist:104,hip:119,arm:36,bodyFat:38},{id:2,student:'Carol Santos',date:'02/08/2026',professor:'João Martins',weight:112,waist:108,hip:121,arm:37,bodyFat:40},{id:3,student:'Juliana Lima',date:'28/08/2026',professor:'Camila Rocha',weight:72,waist:82,hip:101,arm:31,bodyFat:31}];
const TRAINING=[
{id:'legpress',name:'Leg Press 45°',sets:3,reps:'12',load:80,rest:60},
{id:'extensora',name:'Cadeira extensora',sets:3,reps:'12',load:35,rest:45},
{id:'flexora',name:'Mesa flexora',sets:3,reps:'10',load:30,rest:45},
{id:'agachamento',name:'Agachamento no Smith',sets:3,reps:'10',load:40,rest:60}
];
function read(){try{return JSON.parse(localStorage.getItem(STORAGE)||'null')}catch{return null}}
function write(s){try{localStorage.setItem(STORAGE,JSON.stringify(s))}catch{}}
function initials(n){return n.split(' ').map(x=>x[0]).slice(0,2).join('')}
function money(v){return v===0?'R$ 0,00':`R$ ${v.toFixed(2).replace('.',',')}`}
function cap(time,teachers){return teachers.filter(t=>t.active&&t.slots.includes(time)).length*4}
function activeAt(time,teachers){return teachers.filter(t=>t.active&&t.slots.includes(time))}
function suggestTeacher(student,time,teachers,assignments){
 const active=activeAt(time,teachers); const counts=HISTORY[student]||{}; const assigned=Object.values(assignments[time]||{});
 return active.filter(t=>assigned.filter(x=>x===t.name).length<4).sort((a,b)=>(counts[b.name]||0)-(counts[a.name]||0))[0]||null;
}

function App(){
 const p=useMemo(()=>read(),[]);
 const [role,setRole]=useState(p?.role||'student');
 const [screen,setScreen]=useState(p?.screen||'home');
 const [student,setStudent]=useState(p?.student||STUDENTS[0]);
 const [teachers,setTeachers]=useState(p?.teachers||TEACHERS);
 const [students,setStudents]=useState(p?.students||STUDENTS);
 const [bookings,setBookings]=useState(p?.bookings||BOOKINGS);
 const [assignments,setAssignments]=useState(p?.assignments||{'18:00':{'Carol Santos':'João Martins','Ana Souza':'Ana Costa','Paula Mendes':'Camila Rocha','Renato Gomes':'João Martins'}});
 const [attendance,setAttendance]=useState(p?.attendance||{});
 const [waitlist,setWaitlist]=useState(p?.waitlist||{});
 const [assessments,setAssessments]=useState(p?.assessments||ASSESSMENTS);
 const [trainingLog,setTrainingLog]=useState(p?.trainingLog||{});
 const [notices,setNotices]=useState(p?.notices||[]);
 const [toast,setToast]=useState('');
 const [modal,setModal]=useState(null);
 const [first,setFirst]=useState(p?.first??true);
 useEffect(()=>write({role,screen,student,teachers,students,bookings,assignments,attendance,waitlist,assessments,trainingLog,notices,first}),[role,screen,student,teachers,students,bookings,assignments,attendance,waitlist,assessments,trainingLog,notices,first]);
 const notify=m=>{setToast(m);clearTimeout(window.__pf);window.__pf=setTimeout(()=>setToast(''),2600)};
 const updateStudent=patch=>{const next={...student,...patch};setStudent(next);setStudents(s=>s.map(x=>x.id===student.id?next:x));};
 const identify=id=>{setStudents(s=>s.map(x=>x.id===id?{...x,payment:'pago',status:'Ativo'}:x));if(id===student.id)setStudent(s=>({...s,payment:'pago',status:'Ativo'}));notify('Pagamento identificado. Agendamentos liberados.');};
 const book=time=>{if(student.payment==='atrasado'){setScreen('payments');notify('Regularize o pagamento para agendar.');return} const list=bookings[time]||[];if(list.includes(student.name)){notify('Você já está agendado neste horário.');return} if(list.length>=cap(time,teachers)){join(time);return}setBookings(b=>({...b,[time]:[...(b[time]||[]),student.name]}));setStudent(s=>({...s,nextTime:time}));setStudents(xs=>xs.map(x=>x.id===student.id?{...x,nextTime:time}:x));setScreen('appointments');notify(`Treino às ${time} confirmado. O professor será definido pela academia.`)};
 const join=time=>{setWaitlist(w=>({...w,[time]:[...(w[time]||[]),{student:student.name,score:student.frequency,absences:100-student.frequency,cancelNotice:student.frequency}]}));notify(`Você entrou na lista de espera das ${time}.`)};
 const cancel=()=>{if(!student.nextTime){notify('Nenhum treino para cancelar.');return} const t=student.nextTime;setBookings(b=>({...b,[t]:(b[t]||[]).filter(n=>n!==student.name)}));setStudent(s=>({...s,nextTime:null}));notify('Treino cancelado. A vaga foi liberada.');}
 const assign=(time,name,teacher)=>setAssignments(a=>({...a,[time]:{...(a[time]||{}),[name]:teacher}}));
 if(first)return <FirstAccess onContinue={(data)=>{setStudent(s=>({...s,...data}));setStudents(xs=>xs.map(x=>x.id===1?{...x,...data}:x));setFirst(false);notify('Cadastro concluído! Bem-vinda à Power Fit.')}}/>;
 if(role==='professor')return <Professor setRole={setRole} teachers={teachers} students={students} bookings={bookings} assignments={assignments} assessments={assessments} notify={notify} toast={toast}/>;
 if(role==='reception')return <><Reception role={role} setRole={setRole} screen={screen} setScreen={setScreen} teachers={teachers} setTeachers={setTeachers} students={students} setStudents={setStudents} bookings={bookings} setBookings={setBookings} assignments={assignments} assign={assign} attendance={attendance} setAttendance={setAttendance} waitlist={waitlist} setWaitlist={setWaitlist} assessments={assessments} setAssessments={setAssessments} identify={identify} setModal={setModal} notify={notify} toast={toast}/>{modal&&<Modal type={modal} onClose={()=>setModal(null)} onSave={()=>notify('Atendimento presencial registrado com sucesso.')}/>}</>;
 return <Student role={role} setRole={setRole} student={student} screen={screen} setScreen={setScreen} teachers={teachers} bookings={bookings} assignments={assignments} book={book} join={join} cancel={cancel} updateStudent={updateStudent} assessments={assessments} trainingLog={trainingLog} setTrainingLog={setTrainingLog} notices={notices} setNotices={setNotices} setModal={setModal} notify={notify} toast={toast}/>;
}
function Brand({dark=false}){return <div className={'brand '+(dark?'brand-dark':'')}><div className="brand-mark">PF</div><div className="brand-text">POWER <b>FIT</b><small>STUDIO</small></div></div>}
function FirstAccess({onContinue}){const [name,setName]=useState('Carol Santos');const [email,setEmail]=useState('carol.santos@email.com');return <div className="splash"><div className="onboarding"><Brand/><span className="eyebrow">PRIMEIRO ACESSO</span><h1>Seu treino começa aqui.</h1><p>Uma experiência simples para agendar, acompanhar sua evolução e cuidar da sua rotina.</p><div className="welcome-art"><Dumbbell/><Target/><TrendingUp/></div><label>Nome completo<input value={name} onChange={e=>setName(e.target.value)}/></label><label>CPF ou e-mail<input value={email} onChange={e=>setEmail(e.target.value)}/></label><div className="info-box"><ShieldCheck/><span><b>Você escolhe o horário.</b> O professor é definido pela academia de acordo com escala, histórico e capacidade.</span></div><button className="primary-btn full" onClick={()=>onContinue({name,email})}>ENTRAR NO POWER FIT <ChevronRight/></button><small className="demo-note">Modo demonstração • seus dados ficam salvos neste dispositivo</small></div></div>}
function Toast({text}){return <div className="toast"><CheckCircle2/>{text}</div>}
function Student({student,screen,setScreen,teachers,bookings,assignments,book,join,cancel,updateStudent,assessments,trainingLog,setTrainingLog,setModal,notify,toast,setRole}){const [menu,setMenu]=useState(false);const overdue=student.payment==='atrasado';const nextTime=student.nextTime||'18:00';const teacherName=assignments[nextTime]?.[student.name];return <div className="app"><header className="topbar"><Brand/><div className="top-actions"><button className="icon-btn"><Bell/><i>2</i></button><button className="avatar" onClick={()=>setScreen('profile')}>CS</button><button className="icon-btn" onClick={()=>setMenu(!menu)}><Menu/></button></div></header>{menu&&<div className="menu-pop"><button onClick={()=>{setRole('reception');setScreen('dashboard')}}><Settings/> Visão da recepção</button><button onClick={()=>notify('Notificações: 2 novas mensagens')}><Bell/> Notificações</button><button onClick={()=>{localStorage.clear();location.reload()}}><LogOut/> Reiniciar demonstração</button></div>}<main className="mobile-main">{screen==='home'&&<HomeStudent student={student} overdue={overdue} nextTime={nextTime} teacherName={teacherName} setScreen={setScreen}/>} {screen==='booking'&&<Booking student={student} teachers={teachers} bookings={bookings} onBook={book} onJoin={join}/>} {screen==='appointments'&&<Appointments student={student} nextTime={nextTime} teacherName={teacherName} onCancel={cancel} setScreen={setScreen}/>} {screen==='training'&&<TrainingScreen trainingLog={trainingLog} setTrainingLog={setTrainingLog} notify={notify}/>} {screen==='evolution'&&<Evolution student={student} assessments={assessments} setScreen={setScreen}/>} {screen==='payments'&&<PaymentsStudent student={student} onPay={()=>updateStudent({payment:'pago',status:'Ativo'})}/>} {screen==='profile'&&<Profile student={student} updateStudent={updateStudent} setModal={setModal}/>} {screen==='assessments'&&<Assessments assessments={assessments}/>} {screen==='messages'&&<Messages notify={notify}/>}</main><BottomNav screen={screen} setScreen={setScreen}/>{toast&&<Toast text={toast}/>}</div>}
function HomeStudent({student,overdue,nextTime,teacherName,setScreen}){const lost=Math.max(0,student.initialWeight-student.weight);return <><section className="hero"><div className="hero-user"><div className="avatar-lg">CS</div><div><span>Olá, Carol! 👋</span><small>Vamos para mais um treino?</small></div></div><div className="hero-metrics"><div><b>{student.frequency}%</b><span>frequência</span></div><div><b>{student.monthlyWorkouts}</b><span>treinos no mês</span></div><div><b>-{lost} kg</b><span>desde o início</span></div></div></section><div className="page-pad">{overdue&&<div className="alert danger"><AlertCircle/><div><b>Pagamento em atraso</b><span>Seu próximo agendamento está bloqueado até a regularização.</span></div><button onClick={()=>setScreen('payments')}>Regularizar</button></div>}<section className="card featured"><div className="section-head"><span className="label">PRÓXIMO TREINO</span><span className="status-pill">HOJE</span></div><div className="next-info"><div className="exercise-icon"><Dumbbell/></div><div><h2>Musculação</h2><p><Clock3/> {nextTime} • 60 min</p><p className="muted"><UserRound/> {teacherName||'Professor definido pela academia'}</p></div></div><div className="capacity-line"><span>Capacidade do horário</span><b>4 / 4</b></div><button className="primary-btn full" disabled={overdue} onClick={()=>setScreen('appointments')}>{overdue?'AGENDAMENTO BLOQUEADO':'VER MEU TREINO'} <ChevronRight/></button></section><section><div className="section-head title-row"><h3>Acesso rápido</h3></div><div className="quick-grid"><Quick icon={<CalendarDays/>} label="Agendar" onClick={()=>setScreen('booking')}/><Quick icon={<Activity/>} label="Meu treino" onClick={()=>setScreen('training')}/><Quick icon={<TrendingUp/>} label="Evolução" onClick={()=>setScreen('evolution')}/><Quick icon={<CreditCard/>} label="Pagamentos" onClick={()=>setScreen('payments')}/></div></section><section className="card evolution-home"><div className="section-head"><h3>Minha evolução</h3><button onClick={()=>setScreen('evolution')}>Ver tudo <ChevronRight/></button></div><div className="weight-line"><div><small>Peso inicial</small><b>{student.initialWeight} kg</b></div><TrendingDown/><div><small>Atual</small><b>{student.weight} kg</b></div><div className="goal"><small>Meta</small><b>{student.goal} kg</b></div></div><div className="progress"><i style={{width:`${Math.min(100,Math.max(5,((student.initialWeight-student.weight)/(student.initialWeight-student.goal))*100))}%`}}/></div><div className="achievement"><Award/><span><b>Você está evoluindo!</b><small>Continue consistente. A próxima conquista está a caminho.</small></span></div></section><section className="card challenge"><div><span className="label">DESAFIO DO MÊS</span><h3>20 treinos em setembro</h3><p>{student.monthlyWorkouts} de 20 concluídos</p></div><div className="challenge-ring">{Math.min(100,student.monthlyWorkouts*5)}%</div></section></div></>}
function Quick({icon,label,onClick}){return <button className="quick" onClick={onClick}>{icon}<b>{label}</b></button>}
function BottomNav({screen,setScreen}){return <nav className="bottom-nav"><Nav active={screen==='home'} icon={<Home/>} label="Início" onClick={()=>setScreen('home')}/><Nav active={screen==='booking'} icon={<CalendarDays/>} label="Agendar" onClick={()=>setScreen('booking')}/><Nav active={screen==='training'} icon={<Dumbbell/>} label="Treino" onClick={()=>setScreen('training')}/><Nav active={screen==='evolution'||screen==='assessments'} icon={<TrendingUp/>} label="Evolução" onClick={()=>setScreen('evolution')}/><Nav active={screen==='profile'} icon={<UserRound/>} label="Perfil" onClick={()=>setScreen('profile')}/></nav>}
function Nav({active,icon,label,onClick}){return <button className={active?'active':''} onClick={onClick}>{icon}<span>{label}</span></button>}
function PageHeader({icon,title,subtitle,setScreen}){return <div className="page-header"><button className="back" onClick={()=>setScreen?.('home')}><ArrowLeft/></button><div className="page-icon">{icon}</div><div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div></div>}
function Booking({student,teachers,bookings,onBook,onJoin}){const [selected,setSelected]=useState(null);const avail=Object.fromEntries(TIMES.map(t=>[t,Math.max(0,cap(t,teachers)-(bookings[t]?.length||0))]));return <div className="page-pad inner"><PageHeader icon={<CalendarDays/>} title="Agendar treino" subtitle="Você escolhe dia e horário. O professor é definido pela academia."/><div className="date-picker"><button>‹</button><div><small>QUINTA-FEIRA</small><b>10 SET</b></div><button>›</button></div>{student.payment==='atrasado'&&<div className="alert danger"><AlertCircle/><span>Agendamento bloqueado por pagamento em atraso.</span></div>}<div className="rule-banner"><ShieldCheck/><span><b>Distribuição inteligente:</b> a recepção recebe uma sugestão de professor baseada no histórico do aluno.</span></div><h3 className="section-title">Escolha um horário</h3><div className="slots">{TIMES.map(t=>{const full=avail[t]===0;return <button key={t} disabled={student.payment==='atrasado'} className={'slot '+(selected===t?'selected ':'')+(full?'full':'')} onClick={()=>setSelected(t)}><b>{t}</b><span>{full?'LOTADO':`${avail[t]} ${avail[t]===1?'vaga':'vagas'}`}</span>{full&&<em>Lista de espera</em>}</button>})}</div>{selected&&<div className="card confirm-card"><div><small>HORÁRIO SELECIONADO</small><b>{selected} • 60 min</b><span>{avail[selected]?'Professor será atribuído pela recepção':'Este horário está lotado. Entre na lista de espera.'}</span></div><button className="primary-btn" onClick={()=>avail[selected]?onBook(selected):onJoin(selected)}>{avail[selected]?'CONFIRMAR':'ENTRAR NA LISTA'} <Check/></button></div>}<div className="card info-card"><ListChecks/><div><b>Lista de espera inteligente</b><span>A prioridade considera frequência, faltas e antecedência de cancelamentos.</span></div></div></div>}
function Appointments({student,nextTime,teacherName,onCancel,setScreen}){return <div className="page-pad inner"><PageHeader icon={<CalendarDays/>} title="Meus treinos" subtitle="Acompanhe seus próximos horários e histórico."/><div className="tabs"><button className="active">Futuros</button><button>Histórico</button></div><section className="card appointment-card"><div className="appointment-date"><b>QUI</b><strong>10</strong><small>SET</small></div><div className="appointment-body"><span className="status-pill">CONFIRMADO</span><h3>Musculação</h3><p><Clock3/> {nextTime} • 60 min</p><p><UserCheck/> {teacherName||'Professor será definido pela academia'}</p></div><button className="more"><MoreVertical/></button></section><div className="action-row"><button className="outline-btn" onClick={()=>setScreen('booking')}>Reagendar</button><button className="danger-btn" onClick={onCancel}>Cancelar treino</button></div><div className="card cancel-note"><AlertCircle/><span>Cancelamentos feitos com até <b>2 horas de antecedência</b> não contabilizam falta.</span></div></div>}
function TrainingScreen({trainingLog,setTrainingLog,notify}){const [done,setDone]=useState(trainingLog||{});const [feedback,setFeedback]=useState(null);const toggle=(id)=>setDone(d=>({...d,[id]:!d[id]}));const finish=()=>{setTrainingLog(done);setFeedback(true);notify('Treino registrado no histórico!');};return <div className="page-pad inner"><PageHeader icon={<Dumbbell/>} title="Treino de hoje" subtitle="Treino A • Pernas e glúteos"/><div className="card coach-note"><UserCheck/><div><b>Orientação do professor</b><span>Priorize execução controlada e aumente a carga somente se mantiver a técnica.</span></div></div>{TRAINING.map(x=><div className={'card exercise '+(done[x.id]?'done':'')} key={x.id}><div className="exercise-head"><div className="exercise-avatar"><Dumbbell/></div><div><h3>{x.name}</h3><span>{x.sets} séries × {x.reps} • {x.load} kg • {x.rest}s descanso</span></div><button onClick={()=>toggle(x.id)}>{done[x.id]?<CheckCircle2/>:<span className="empty-check"/>}</button></div><div className="set-row">{Array.from({length:x.sets}).map((_,i)=><div key={i}><small>Série {i+1}</small><input defaultValue={x.load}/><span>kg</span></div>)}</div></div>)}<button className="primary-btn full finish" onClick={finish}><CheckCircle2/> FINALIZAR TREINO</button>{feedback&&<div className="card feedback"><Star/><div><b>Como foi seu treino?</b><span>Seu feedback ajuda a equipe a acompanhar sua experiência.</span><div className="stars">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>setFeedback(false)}><Star/></button>)}</div></div></div>}</div>}
function Evolution({student,assessments,setScreen}){const mine=assessments.filter(a=>a.student===student.name);const lost=student.initialWeight-student.weight;return <div className="page-pad inner"><PageHeader icon={<TrendingUp/>} title="Evolução" subtitle="Seus resultados, frequência e desempenho em um só lugar."/><div className="card evolution-hero"><span className="label">PESO</span><div className="big-number">{student.weight} <small>kg</small></div><div className="delta"><TrendingDown/> {lost} kg desde o início</div><div className="chart"><i/><i/><i/><i/><i/><i/><i/></div></div><div className="metrics-3"><Metric icon={<Target/>} value={`${student.goal} kg`} label="Meta"/><Metric icon={<CalendarDays/>} value={`${student.frequency}%`} label="Frequência"/><Metric icon={<Zap/>} value={student.monthlyWorkouts} label="Treinos no mês"/></div><div className="card measures"><div className="section-head"><h3>Medidas</h3><span>Última avaliação</span></div>{mine[0]?<div className="measure-grid"><Measure l="Cintura" v={`${mine[0].waist} cm`}/><Measure l="Quadril" v={`${mine[0].hip} cm`}/><Measure l="Braço" v={`${mine[0].arm} cm`}/><Measure l="Gordura" v={`${mine[0].bodyFat}%`}/></div>:<p>Nenhuma avaliação registrada.</p>}<button className="text-btn" onClick={()=>setScreen('assessments')}>Ver histórico de avaliações <ChevronRight/></button></div><div className="card achievements"><div className="section-head"><h3>Conquistas</h3><Award/></div><div className="badges"><Badge icon="🏋️" text="50 treinos"/><Badge icon="🔥" text="30 dias"/><Badge icon="📈" text="Evolução"/><Badge icon="⭐" text="Frequente"/></div></div></div>}
function Metric({icon,value,label}){return <div className="metric"><div>{icon}</div><b>{value}</b><span>{label}</span></div>}
function Measure({l,v}){return <div><small>{l}</small><b>{v}</b></div>}
function Badge({icon,text}){return <div><span>{icon}</span><b>{text}</b></div>}
function Assessments({assessments}){return <div className="page-pad inner"><PageHeader icon={<FileText/>} title="Avaliações" subtitle="Histórico das suas avaliações físicas."/>{assessments.filter(a=>a.student==='Carol Santos').map(a=><div className="card assessment" key={a.id}><div className="assessment-top"><div><span>{a.date}</span><b>{a.professor}</b></div><span className="status-pill">AVALIAÇÃO</span></div><div className="measure-grid"><Measure l="Peso" v={`${a.weight} kg`}/><Measure l="Cintura" v={`${a.waist} cm`}/><Measure l="Quadril" v={`${a.hip} cm`}/><Measure l="Gordura" v={`${a.bodyFat}%`}/></div></div>)}</div>}
function PaymentsStudent({student,onPay}){const [paid,setPaid]=useState(student.payment==='pago');return <div className="page-pad inner"><PageHeader icon={<CreditCard/>} title="Pagamentos" subtitle="Acompanhe sua situação financeira e histórico."/><div className={'payment-status '+(student.payment==='pago'?'ok':'late')}><div>{student.payment==='pago'?<CheckCircle2/>:<AlertCircle/>}</div><span>{student.payment==='pago'?'Pagamento em dia':'Pagamento em atraso'}</span><b>{student.payment==='pago'?'Tudo certo!':'Ação necessária'}</b></div><div className="card bill"><div><span>Próxima mensalidade</span><h2>{money(student.value)}</h2><p>Vencimento: {student.due}</p></div><Wallet/><button className="primary-btn" onClick={()=>{setPaid(true);onPay()}}>{student.payment==='pago'?'VER COMPROVANTE':'REGULARIZAR AGORA'}</button></div><div className="card payment-options"><h3>Formas de pagamento</h3><button><QrCode/><span><b>PIX</b><small>Pagamento instantâneo</small></span><ChevronRight/></button><button><CreditCard/><span><b>Cartão</b><small>Crédito ou débito</small></span><ChevronRight/></button></div><div className="card plan-card"><div><span>Seu plano</span><b>{student.plan}</b></div><button>Solicitar alteração</button></div></div>}
function Profile({student,updateStudent,setModal}){const [w,setW]=useState(student.weight);const [g,setG]=useState(student.goal);return <div className="page-pad inner"><PageHeader icon={<UserRound/>} title="Meu perfil" subtitle="Seus dados e preferências."/><div className="profile-head card"><div className="profile-photo">CS<button><Camera/></button></div><div><h2>{student.name}</h2><span>{student.email}</span><small>Aluno desde 2025</small></div></div><div className="card form-card"><h3>Dados físicos</h3><label>Altura (m)<input value={student.height} onChange={e=>updateStudent({height:e.target.value})}/></label><div className="two"><label>Peso atual<input value={w} onChange={e=>{setW(e.target.value);updateStudent({weight:Number(e.target.value)})}}/></label><label>Meta de peso<input value={g} onChange={e=>{setG(e.target.value);updateStudent({goal:Number(e.target.value)})}}/></label></div></div><div className="card menu-list"><button><UserRound/><span>Meus dados</span><ChevronRight/></button><button><CreditCard/><span>Meu plano • {student.plan}</span><ChevronRight/></button><button><Bell/><span>Notificações</span><span className="toggle on">●</span></button><button><MessageCircle/><span>Ajuda e suporte</span><ChevronRight/></button></div></div>}
function Messages({notify}){return <div className="page-pad inner"><PageHeader icon={<MessageCircle/>} title="Mensagens" subtitle="Comunicação da Power Fit com você."/><div className="card message"><div className="message-icon"><Cake/></div><div><small>Hoje</small><h3>Feliz aniversário! 🎉</h3><p>Que seu novo ciclo venha com muita saúde, energia e conquistas.</p><button className="text-btn" onClick={()=>notify('Mensagem marcada como lida')}>Marcar como lida</button></div></div><div className="card message"><div className="message-icon"><Dumbbell/></div><div><small>Ontem</small><h3>Novo desafio do mês</h3><p>20 treinos em setembro. Bora completar?</p></div></div></div>}
function Professor({setRole,teachers,students,bookings,assignments,assessments,notify,toast}){const [tab,setTab]=useState('today');const me=teachers.find(t=>t.id===1)||teachers[0];const names=Object.entries(assignments['18:00']||{}).filter(([,p])=>p===me.name).map(([n])=>n);return <div className="reception"><header className="reception-top"><button className="icon-btn" onClick={()=>setRole('reception')}><ArrowLeft/></button><Brand dark/><div className="admin-avatar">JM</div></header><main className="admin-pad"><div className="admin-title"><div><span>ÁREA DO PROFESSOR</span><h1>Olá, João 👋</h1><p>Acompanhe seus alunos, fichas e avaliações.</p></div></div><div className="teacher-tabs"><button className={tab==='today'?'active':''} onClick={()=>setTab('today')}>Hoje</button><button className={tab==='students'?'active':''} onClick={()=>setTab('students')}>Meus alunos</button><button className={tab==='assessments'?'active':''} onClick={()=>setTab('assessments')}>Avaliações</button></div>{tab==='today'&&<><div className="card teacher-hero"><div><span>PRÓXIMO HORÁRIO</span><b>18:00</b><small>{names.length} alunos • capacidade 4</small></div><Dumbbell/></div><h2 className="section-title">Alunos das 18:00</h2>{names.map(n=><div className="card prof-student" key={n}><div>{initials(n)}</div><span><b>{n}</b><small>Ficha de treino • evolução disponível</small></span><button onClick={()=>notify('Ficha de '+n+' aberta para consulta.')}><ChevronRight/></button></div>)}</>}{tab==='students'&&students.filter(s=>s.status==='Ativo').map(s=><div className="card prof-student" key={s.id}><div>{initials(s.name)}</div><span><b>{s.name}</b><small>{s.frequency}% frequência • {s.weight} kg</small></span><button onClick={()=>notify('Perfil do aluno aberto.')}>Ver</button></div>)}{tab==='assessments'&&assessments.map(a=><div className="card assessment" key={a.id}><div className="assessment-top"><div><span>{a.date}</span><b>{a.student}</b></div><span className="status-pill">{a.professor}</span></div><div className="measure-grid"><Measure l="Peso" v={a.weight+' kg'}/><Measure l="Cintura" v={a.waist+' cm'}/><Measure l="Gordura" v={a.bodyFat+'%'}/><Measure l="Quadril" v={a.hip+' cm'}/></div></div>)}{toast&&<Toast text={toast}/>}</main></div>}
function Reception({setRole,screen,setScreen,teachers,setTeachers,students,setStudents,bookings,setBookings,assignments,assign,attendance,setAttendance,waitlist,setWaitlist,assessments,setAssessments,identify,setModal,notify,toast}){const [open,setOpen]=useState(false);const [selectedTime,setSelectedTime]=useState('18:00');const [search,setSearch]=useState('');const [profTab,setProfTab]=useState(null);const today=students.filter(s=>s.birthday.endsWith('-09-07'));const month=students.filter(s=>s.birthday.includes('-09-'));const overdue=students.filter(s=>s.payment==='atrasado');return <div className="reception"><header className="reception-top"><button className="icon-btn" onClick={()=>setOpen(!open)}><Menu/></button><Brand dark/><div className="top-actions"><button className="icon-btn"><Bell/><i>4</i></button><div className="admin-avatar">RF</div></div></header>{open&&<div className="reception-menu">{[['dashboard','Dashboard',Home],['agenda','Agenda',CalendarDays],['students','Alunos',Users],['teachers','Professores',UserCheck],['payments','Pagamentos',Wallet],['waitlist','Lista de espera',ListChecks],['reports','Relatórios',TrendingUp],['settings','Configurações',Settings],['professor','Visão do professor',UserCheck]].map(([id,l,I])=><button key={id} className={screen===id?'active':''} onClick={()=>{setScreen(id);setOpen(false)}}><I/>{l}</button>)}<button onClick={()=>setRole('student')}><LogOut/> Voltar para aluno</button></div>}<main className="reception-main">{screen==='dashboard'&&<Dashboard students={students} teachers={teachers} bookings={bookings} today={today} overdue={overdue} setScreen={setScreen}/>} {screen==='agenda'&&<Agenda selectedTime={selectedTime} setSelectedTime={setSelectedTime} teachers={teachers} bookings={bookings} assignments={assignments} assign={assign} attendance={attendance} setAttendance={setAttendance} notify={notify}/>} {screen==='students'&&<StudentsAdmin students={students} setStudents={setStudents} search={search} setSearch={setSearch} notify={notify}/>} {screen==='teachers'&&<TeachersAdmin teachers={teachers} setTeachers={setTeachers} notify={notify}/>} {screen==='payments'&&<PaymentsAdmin students={students} identify={identify} setModal={setModal} notify={notify}/>} {screen==='waitlist'&&<WaitlistAdmin waitlist={waitlist} setWaitlist={setWaitlist}/>} {screen==='reports'&&<Reports students={students} teachers={teachers} bookings={bookings}/>} {screen==='settings'&&<SettingsAdmin teachers={teachers} setTeachers={setTeachers}/>} </main>{toast&&<Toast text={toast}/>}</div>}
function Dashboard({students,teachers,bookings,today,overdue,setScreen}){const total=Object.values(bookings).reduce((a,b)=>a+b.length,0);const active=teachers.filter(t=>t.active).length;return <div className="admin-pad"><div className="admin-hello"><div><span>PAINEL POWER FIT</span><h1>Boa tarde, Recepção 👋</h1><p>Visão geral da academia em tempo real.</p></div><button className="primary-btn" onClick={()=>setScreen('agenda')}><CalendarDays/> Agenda de hoje</button></div><div className="kpi-grid"><Kpi icon={<Users/>} label="Alunos ativos" value={students.filter(s=>s.status==='Ativo').length}/><Kpi icon={<CalendarDays/>} label="Treinos hoje" value={total}/><Kpi icon={<UserCheck/>} label="Professores ativos" value={active}/><Kpi icon={<AlertCircle/>} label="Inadimplentes" value={overdue.length} danger/></div>{today.length>0&&<div className="admin-alert birthday"><Cake/><div><b>🎉 Aniversariantes de hoje</b><span>{today.map(s=>s.name).join(' • ')}</span></div><button onClick={()=>setScreen('students')}>Ver alunos</button></div>}<section className="admin-section"><div className="section-head"><h2>Operação de hoje</h2><button onClick={()=>setScreen('agenda')}>Abrir agenda <ChevronRight/></button></div><div className="mini-agenda">{['06:00','07:00','08:00','18:00','19:00'].map(t=>{const c=bookings[t]?.length||0;const capacity=cap(t,teachers);return <button key={t} onClick={()=>setScreen('agenda')}><b>{t}</b><span>{c}/{capacity}</span><i style={{width:`${Math.min(100,c/capacity*100)}%`}}/></button>})}</div></section><section className="admin-section"><div className="section-head"><h2>Alertas que precisam de atenção</h2></div><div className="alert-list"><button onClick={()=>setScreen('payments')}><AlertCircle/><span><b>{overdue.length} pagamentos em atraso</b><small>Identifique ou entre em contato com os alunos.</small></span><ChevronRight/></button><button onClick={()=>setScreen('waitlist')}><ListChecks/><span><b>6 alunos na lista de espera</b><small>Uma vaga pode ser liberada a qualquer momento.</small></span><ChevronRight/></button><button onClick={()=>setScreen('students')}><TrendingDown/><span><b>5 alunos com queda de frequência</b><small>O sistema recomenda uma ação de retenção.</small></span><ChevronRight/></button></div></section><section className="admin-section"><div className="section-head"><h2>Saúde da academia</h2><span>Setembro</span></div><div className="health-grid"><div><small>Frequência média</small><b>79%</b><em>+4,2%</em></div><div><small>Retenção</small><b>92%</b><em>+1,8%</em></div><div><small>Satisfação</small><b>4,7/5</b><em>+0,3</em></div></div></section></div>}
function Kpi({icon,label,value,danger}){return <div className={'kpi '+(danger?'danger':'')}><div>{icon}</div><span>{label}</span><b>{value}</b></div>}
function Agenda({selectedTime,setSelectedTime,teachers,bookings,assignments,assign,attendance,setAttendance,notify}){const list=bookings[selectedTime]||[];const available=activeAt(selectedTime,teachers);return <div className="admin-pad"><div className="admin-title"><div><span>AGENDA</span><h1>Hoje • 10 de setembro</h1><p>Agenda por horário. Clique para abrir os alunos.</p></div></div><div className="time-strip">{TIMES.map(t=><button className={selectedTime===t?'active':''} key={t} onClick={()=>setSelectedTime(t)}><b>{t}</b><span>{bookings[t]?.length||0}/{cap(t,teachers)}</span></button>)}</div><div className="slot-summary"><div><span>Horário selecionado</span><b>{selectedTime}</b></div><div><span>Ocupação</span><b>{list.length}/{cap(selectedTime,teachers)}</b></div><div><span>Professores</span><b>{available.length}</b></div></div><div className="admin-note"><ShieldCheck/><span><b>Distribuição inteligente:</b> o sistema sugere o professor disponível com maior histórico de treinos com cada aluno, respeitando o limite de 4.</span></div><section className="student-bookings"><div className="section-head"><h2>{list.length} alunos agendados</h2><span>{selectedTime}</span></div>{list.length===0?<div className="empty">Nenhum agendamento neste horário.</div>:list.map(name=>{const suggestion=suggestTeacher(name,selectedTime,teachers,assignments);const selected=assignments[selectedTime]?.[name]||suggestion?.name;const a=attendance[`${selectedTime}-${name}`];const counts=HISTORY[name]||{};return <div className="booking-row" key={name}><div className="student-mini"><div>{initials(name)}</div><span><b>{name}</b><small>Histórico: {selected||'sem professor'}</small></span></div><div className="suggestion"><small>SUGESTÃO</small><b>{suggestion?.name||'Sem disponibilidade'}</b><span>{suggestion?`${counts[suggestion.name]||0} treinos com este aluno`:''}</span></div><div className="prof-select"><label>Direcionar para</label><select value={selected||''} onChange={e=>assign(selectedTime,name,e.target.value)}>{available.map(t=><option key={t.id} value={t.name}>{t.name} • {counts[t.name]||0}x</option>)}</select></div><div className="attendance-inline"><span className={a==='present'?'present':a==='absent'?'absent':'pending'}>{a==='present'?'Presente':a==='absent'?'Falta':'Pendente'}</span><button onClick={()=>setAttendance(x=>({...x,[`${selectedTime}-${name}`]:'present'}))} disabled={!canMark(selectedTime)}><Check/></button><button onClick={()=>setAttendance(x=>({...x,[`${selectedTime}-${name}`]:'absent'}))} disabled={!canMark(selectedTime)}><X/></button></div></div>})}</section><div className="admin-foot-note"><Clock3/> Presença/falta fica disponível quando o horário estiver dentro da janela de atendimento informada pela academia.</div></div>}
function canMark(time){return time==='18:00'}
function StudentsAdmin({students,setStudents,search,setSearch,notify}){const [sel,setSel]=useState(null);const filtered=students.filter(s=>s.name.toLowerCase().includes(search.toLowerCase()));return <div className="admin-pad"><div className="admin-title"><div><span>ALUNOS</span><h1>Gestão de alunos</h1><p>Cadastro, perfil, frequência e retenção.</p></div><button className="primary-btn" onClick={()=>notify('Novo aluno: formulário de cadastro preparado.')}> <Plus/> Novo aluno</button></div><div className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar aluno..."/></div><div className="student-list-admin">{filtered.map(s=><button key={s.id} onClick={()=>setSel(s.id)} className="admin-student-card"><div>{initials(s.name)}</div><span><b>{s.name}</b><small>{s.plan} • {s.frequency}% frequência</small></span><em className={s.payment==='atrasado'?'red':''}>{s.payment==='atrasado'?'Em atraso':'Em dia'}</em><ChevronRight/></button>)}</div>{sel&&<StudentDrawer student={students.find(x=>x.id===sel)} onClose={()=>setSel(null)} setStudents={setStudents} notify={notify}/>}</div>}
function StudentDrawer({student,onClose,setStudents,notify}){const [plan,setPlan]=useState(student.plan);return <div className="drawer-back"><div className="drawer"><button className="drawer-close" onClick={onClose}><X/></button><div className="drawer-head"><div>{initials(student.name)}</div><h2>{student.name}</h2><span>{student.email||'aluno@powerfit.com'}</span></div><div className="drawer-metrics"><div><b>{student.weight}</b><small>kg</small></div><div><b>{student.frequency}%</b><small>frequência</small></div><div><b>{student.monthlyWorkouts}</b><small>treinos/mês</small></div></div><label>Modalidade<select value={plan} onChange={e=>{setPlan(e.target.value);setStudents(xs=>xs.map(x=>x.id===student.id?{...x,plan:e.target.value}:x));notify('Modalidade atualizada.')}}><option>Plano Mensal</option><option>TotalPass</option><option>Wellhub</option><option>Plano Trimestral</option></select></label><div className="drawer-actions"><button onClick={()=>notify('Mensagem enviada para o aluno.')}>Enviar mensagem</button><button onClick={()=>notify('Ficha de treino aberta para edição.')}>Ficha de treino</button><button onClick={()=>notify('Aluno marcado para acompanhamento.')}>Acompanhar retenção</button></div><div className="audit">Última atualização: hoje às 18:42</div></div></div>}
function TeachersAdmin({teachers,setTeachers,notify}){return <div className="admin-pad"><div className="admin-title"><div><span>PROFESSORES</span><h1>Equipe e escala</h1><p>Capacidade automática: 4 alunos por professor.</p></div><button className="primary-btn" onClick={()=>setTeachers(t=>[...t,{id:Date.now(),name:'Novo Professor',active:true,slots:['18:00']}])}><Plus/> Novo professor</button></div>{teachers.map(t=><div className="teacher-card" key={t.id}><div className={'teacher-avatar '+(!t.active?'off':'')}>{initials(t.name)}</div><div className="teacher-info"><b>{t.name}</b><span>{t.active?'Ativo':'Inativo'} • {t.slots.length} horários</span><div className="chips">{t.slots.map(x=><i key={x}>{x}</i>)}</div></div><button className={'switch '+(t.active?'on':'')} onClick={()=>setTeachers(ts=>ts.map(x=>x.id===t.id?{...x,active:!x.active}:x))}><span/></button></div>)}<div className="card capacity-explainer"><Users/><div><b>Capacidade dinâmica</b><span>Se houver 3 professores ativos às 18h, o horário terá 12 vagas. Se um professor mudar de escala, as vagas são recalculadas automaticamente.</span></div></div></div>}
function PaymentsAdmin({students,identify,setModal,notify}){const overdue=students.filter(s=>s.payment==='atrasado');return <div className="admin-pad"><div className="admin-title"><div><span>FINANCEIRO</span><h1>Pagamentos</h1><p>Mensalidades, inadimplência e atendimentos presenciais.</p></div><button className="primary-btn" onClick={()=>setModal('dayuse')}><Plus/> Day use / experimental</button></div><div className="finance-kpis"><Kpi icon={<Wallet/>} label="Recebido" value="R$ 18.450"/><Kpi icon={<AlertCircle/>} label="Em aberto" value="R$ 2.398" danger/><Kpi icon={<UserX/>} label="Inadimplentes" value={overdue.length} danger/></div>{students.map(s=><div className="payment-row" key={s.id}><div>{initials(s.name)}</div><span><b>{s.name}</b><small>{s.plan} • {money(s.value)} • vence {s.due}</small></span><button className={s.payment==='pago'?'identified':''} onClick={()=>identify(s.id)}>{s.payment==='pago'?<><CheckCircle2/> Identificado</>:<><Check/> Identificar pagamento</>}</button></div>)}</div>}
function WaitlistAdmin({waitlist,setWaitlist}){const all=Object.entries(waitlist).flatMap(([time,items])=>items.map((x,i)=>({...x,time,position:i+1}))).sort((a,b)=>b.score-a.score);return <div className="admin-pad"><div className="admin-title"><div><span>LISTA DE ESPERA</span><h1>Vagas e prioridade</h1><p>Prioridade por frequência, faltas e antecedência de cancelamentos.</p></div></div>{all.length?all.map((x,i)=><div className="wait-row" key={x.time+x.student}><div className="rank">{i+1}</div><span><b>{x.student}</b><small>{x.time} • frequência {x.score}%</small></span><em>Prioridade alta</em><button onClick={()=>setWaitlist(w=>({...w,[x.time]:(w[x.time]||[]).filter(y=>y.student!==x.student)}))}>Convocar</button></div>):<div className="empty">Nenhum aluno aguardando.</div>}<div className="card rule-card"><ListChecks/><div><b>Como o sistema decide?</b><span>Maior frequência + menos faltas + melhor histórico de cancelamento com antecedência.</span></div></div></div>}
function Reports({students,teachers,bookings}){return <div className="admin-pad"><div className="admin-title"><div><span>RELATÓRIOS</span><h1>Indicadores da academia</h1><p>Visão de operação, retenção e performance.</p></div></div><div className="report-card"><h3>Frequência por mês</h3><div className="bars">{[62,70,68,76,73,79,82].map((x,i)=><div key={i}><i style={{height:`${x}%`}}/><small>{['Mar','Abr','Mai','Jun','Jul','Ago','Set'][i]}</small></div>)}</div></div><div className="report-grid"><Report label="Alunos ativos" value={students.filter(s=>s.status==='Ativo').length} trend="+6%"/><Report label="Taxa de retenção" value="92%" trend="+1,8%"/><Report label="Ocupação média" value="78%" trend="+5%"/><Report label="Satisfação" value="4,7/5" trend="+0,3"/></div><div className="card report-list"><h3>Oportunidades de retenção</h3>{students.filter(s=>s.frequency<70).map(s=><div key={s.id}><TrendingDown/><span><b>{s.name}</b><small>Frequência caiu para {s.frequency}%</small></span><button>Acionar</button></div>)}</div></div>}
function Report({label,value,trend}){return <div className="report-mini"><small>{label}</small><b>{value}</b><em>{trend}</em></div>}
function SettingsAdmin({teachers,setTeachers}){const [cancel,setCancel]=useState(2);return <div className="admin-pad"><div className="admin-title"><div><span>CONFIGURAÇÕES</span><h1>Regras da academia</h1><p>Parâmetros que controlam a operação do Power Fit.</p></div></div><div className="settings-list"><div><Users/><span><b>Capacidade por professor</b><small>Máximo de alunos por professor por horário</small></span><strong>4</strong></div><div><Clock3/><span><b>Antecedência para cancelar</b><small>Treino não contabiliza falta até o prazo definido</small></span><input type="number" value={cancel} onChange={e=>setCancel(e.target.value)}/><b>h</b></div><div><Zap/><span><b>Recalcular capacidade automaticamente</b><small>Escala dos professores altera as vagas</small></span><span className="toggle on">●</span></div><div><CreditCard/><span><b>Bloqueio por inadimplência</b><small>Impede novos agendamentos até identificação do pagamento</small></span><span className="toggle on">●</span></div><div><UserCheck/><span><b>Professor sugerido por histórico</b><small>Prioriza o professor com maior número de treinos anteriores</small></span><span className="toggle on">●</span></div></div></div>}
function Modal({type,onClose,onSave}){if(type!=='dayuse')return null;const [name,setName]=useState('');const [kind,setKind]=useState('Day use');const [value,setValue]=useState('30');return <div className="modal-back"><div className="modal"><button onClick={onClose}><X/></button><span className="eyebrow">POWER FIT • RECEPÇÃO</span><h2>Atendimento presencial</h2><p>Registre um Day Use ou aluno experimental que pagou na recepção.</p><label>Nome<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome do visitante"/></label><div className="two"><label>Tipo<select value={kind} onChange={e=>setKind(e.target.value)}><option>Day use</option><option>Aluno experimental</option></select></label><label>Valor<input value={value} onChange={e=>setValue(e.target.value)}/></label></div><button className="primary-btn full" onClick={()=>{onSave?.({name:name||'Visitante',kind,value});onClose()}}>REGISTRAR PAGAMENTO <Check/></button></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
